services:
    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        ports:
            - 5173:5173
        logging:
            driver: 'json-file'
            options:
                max-size: '100m'
                max-file: '10'
                tag: '{{.ImageName}}|{{.Name}}'
    backend:
        build: ./backend
        container_name: backend
        restart: always
        ports:
            - 2050:2050
        logging:
            driver: 'json-file'
            options:
                max-size: '100m'
                max-file: '10'
                tag: '{{.ImageName}}|{{.Name}}'
